# steps:
# - name: 'gcr.io/cloud-builders/docker'
#   args: [ 'build', '-t', 'us-west2-docker.pkg.dev/stock-prices-project/stock-prices-repo/stock-image:latest', '.' ]
# images:
# - 'us-west2-docker.pkg.dev/stock-prices-project/stock-prices-repo/stock-image:latest'
# timeout: 14400s
steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --destination=us-west2-docker.pkg.dev/stock-prices-project/stock-prices-repo/stock-image:latest
  - --cache=true
  - --cache-ttl=24h
  id: image
- name: gcr.io/cloud-builders/gcloud
  entrypoint: "bash"
  args:
  - "-c"
  - |
      gcloud run deploy stock-image \
        --image=us-west2-docker.pkg.dev/stock-prices-project/stock-prices-repo/stock-image:latest \
        --platform=managed \
        --region=us-west2 \
        --project=stock-prices-project
  waitFor: ['image']
# options:
    # machineType: 'E2_HIGHCPU_32'
timeout: 14400s