steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - daily_stock_prices #Function name
  - --region=us-west2
  - --source=stock_prices # git name
  - --trigger-http 

timeout: 14400s